import sqlite3
import random
from datetime import datetime, timedelta
from lead_intelligence.scoring import recalculate_and_persist_score

DB_PATH = "lead_system.db"

conn = sqlite3.connect(DB_PATH)
conn.row_factory = sqlite3.Row
cursor = conn.cursor()

names = [
    "Sarah Jenkins", "Michael Chen", "Aisha Patel", "David Torres",
    "Emma Washington", "James O'Connor", "Priya Singh", "Robert Kim",
    "Fatima Al-Sayed", "William Taylor", "Olivia Martinez", "Lucas Silva",
    "Sophia Reynolds", "Alexander White", "Isabella Gupta", "Daniel Brown",
    "Mia Nguyen", "Ethan Clark", "Ava Robinson", "Noah Lewis"
]

domains = ["techcorp.io", "globalsolutions.net", "innovate.com", "enterprise.org", "startup.co"]
statuses = ["new", "contacted", "interested", "applied", "admitted", "lost"]
priorities = ["high", "medium", "low"]
cities = ["New York", "San Francisco", "London", "Toronto", "Mumbai", "Sydney", "Berlin", "Dubai"]
courses = ["Strategic Management", "Cloud Architecture", "Data Science", "UX Design", "Cybersecurity", "Artificial Intelligence", "Corporate Fin."]
lead_sources = ["Website", "Referral", "Walk-in", "Social Media", "Advertisement", "Other"]

def generate_professional_email(name):
    try:
        first, last = name.split(" ", 1)
        last = last.replace("'", "").replace("-", "")
    except:
        first = name
        last = ""
    formats = [
        f"{first.lower()}.{last.lower()}",
        f"{first.lower()[0]}{last.lower()}",
        f"{first.lower()}_{last.lower()}"
    ]
    return f"{random.choice(formats)}@{random.choice(domains)}"

def generate_phone_number():
    # Generate a realistic 10-digit phone number in the format XXX-XXX-XXXX
    area = random.randint(200, 999)
    prefix = random.randint(200, 999)
    line = random.randint(1000, 9999)
    return f"{area}-{prefix}-{line}"


def seed_leads():
    for name in names:
        email = generate_professional_email(name)
        phone_contact = generate_phone_number()
        city = random.choice(cities)
        course = random.choice(courses)
        priority = random.choice(priorities)
        status = random.choice(statuses)
        lead_source = random.choice(lead_sources)
        notes = "Generated by seed script."
        created_at = (datetime.now() - timedelta(days=random.randint(0, 30))).strftime("%Y-%m-%d %H:%M:%S")
        
        try:
            cursor.execute('''
                INSERT INTO leads (student_name, phone, city, course_interest, lead_source, interest_level, status, notes, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (name, phone_contact, city, course, lead_source, priority, status, notes, created_at))
            
            lead_id = cursor.lastrowid
            
            # Create random interactions so the seed data exercises scoring and follow-up widgets
            if random.random() > 0.4:  # 60% chance to have interaction
                for _ in range(random.randint(1, 3)):
                    int_type = random.choice(["call", "email", "whatsapp", "visit"])
                    int_notes = "Spoke about course structure."
                    int_created_at = (datetime.now() - timedelta(days=random.randint(1, 40))).strftime("%Y-%m-%d %H:%M:%S")
                    
                    # 30% chance for an upcoming follow-up to populate that widget
                    follow_up_date = None
                    if random.random() > 0.7:
                        follow_up_date = (datetime.now().date() + timedelta(days=random.randint(0, 7))).strftime("%Y-%m-%d")
                    
                    cursor.execute('''
                        INSERT INTO interactions (lead_id, interaction_type, notes, follow_up_date, created_at)
                        VALUES (?, ?, ?, ?, ?)
                    ''', (lead_id, int_type, int_notes, follow_up_date, int_created_at))

            # Recalculate each lead's score using the live scoring algorithm.
            recalculate_and_persist_score(conn, lead_id)

        except Exception as e:
            print(f"Error inserting {name}: {e}")

if __name__ == "__main__":
    
    # Optionally clear previous leads for a fresh presentation state
    cursor.execute("DELETE FROM leads")
    cursor.execute("DELETE FROM interactions")
    
    seed_leads()
    conn.commit()
    print("Successfully seeded database with 20 realistic leads for the presentation!")
    conn.close()
