import sqlite3
import random
from datetime import datetime, timedelta

DB_PATH = "lead_system.db"

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

names = [
    "Sarah Jenkins", "Michael Chen", "Aisha Patel", "David Torres",
    "Emma Washington", "James O'Connor", "Priya Singh", "Robert Kim",
    "Fatima Al-Sayed", "William Taylor", "Olivia Martinez", "Lucas Silva",
    "Sophia Reynolds", "Alexander White", "Isabella Gupta", "Daniel Brown",
    "Mia Nguyen", "Ethan Clark", "Ava Robinson", "Noah Lewis"
]

domains = ["techcorp.io", "globalsolutions.net", "innovate.com", "enterprise.org", "startup.co"]
statuses = ["new", "contacted", "interested", "applied", "admitted", "lost"]
priorities = ["high", "medium", "low"]
cities = ["New York", "San Francisco", "London", "Toronto", "Mumbai", "Sydney", "Berlin", "Dubai"]
courses = ["Strategic Management", "Cloud Architecture", "Data Science", "UX Design", "Cybersecurity", "Artificial Intelligence", "Corporate Fin."]

def generate_professional_email(name):
    try:
        first, last = name.split(" ", 1)
        last = last.replace("'", "").replace("-", "")
    except:
        first = name
        last = ""
    formats = [
        f"{first.lower()}.{last.lower()}",
        f"{first.lower()[0]}{last.lower()}",
        f"{first.lower()}_{last.lower()}"
    ]
    return f"{random.choice(formats)}@{random.choice(domains)}"

def seed_leads():
    for name in names:
        email = generate_professional_email(name)
        # Using phone string to hold both Phone and Email so it displays beautifully on the Contact Info card
        phone_contact = f"{email}"
        city = random.choice(cities)
        course = random.choice(courses)
        priority = random.choice(priorities)
        status = random.choice(statuses)
        notes = "Generated by seed script."
        created_at = (datetime.now() - timedelta(days=random.randint(0, 30))).strftime("%Y-%m-%d %H:%M:%S")
        
        try:
            cursor.execute('''
                INSERT INTO leads (student_name, phone, city, course_interest, interest_level, status, notes, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ''', (name, phone_contact, city, course, priority, status, notes, created_at))
            
            lead_id = cursor.lastrowid
            
            # Since lead_score is dynamically built by interactions normally, we'll manually set it for data visualization 
            # to trigger 'hot', 'warm', 'cold' categories beautifully!
            score = 0
            if priority == "high": score += random.randint(50, 95)
            elif priority == "medium": score += random.randint(30, 60)
            else: score += random.randint(0, 30)
                
            cursor.execute("UPDATE leads SET lead_score = ? WHERE lead_id = ?", (score, lead_id))
            
            # Let's also create random interactions so "Upcoming Follow-ups" and "Neglected Leads" works
            if random.random() > 0.4:  # 60% chance to have interaction
                for _ in range(random.randint(1, 3)):
                    int_type = random.choice(["call", "email", "whatsapp", "visit"])
                    int_notes = "Spoke about course structure."
                    int_created_at = (datetime.now() - timedelta(days=random.randint(1, 40))).strftime("%Y-%m-%d %H:%M:%S")
                    
                    # 30% chance for an upcoming follow-up to populate that widget
                    follow_up_date = None
                    if random.random() > 0.7:
                        follow_up_date = (datetime.now().date() + timedelta(days=random.randint(0, 7))).strftime("%Y-%m-%d")
                    
                    cursor.execute('''
                        INSERT INTO interactions (lead_id, interaction_type, notes, follow_up_date, created_at)
                        VALUES (?, ?, ?, ?, ?)
                    ''', (lead_id, int_type, int_notes, follow_up_date, int_created_at))

        except Exception as e:
            print(f"Error inserting {name}: {e}")

if __name__ == "__main__":
    
    # Optionally clear previous leads for a fresh presentation state
    cursor.execute("DELETE FROM leads")
    cursor.execute("DELETE FROM interactions")
    
    seed_leads()
    conn.commit()
    print("Successfully seeded database with 20 realistic leads for the presentation!")
    conn.close()
