import random
from datetime import datetime, timedelta
from app import create_app
from database.db_connection import get_db
from database.models import Lead, Interaction
from modules.scoring_engine import recalculate_and_persist_score

names = [
    "Sarah Jenkins", "Michael Chen", "Aisha Patel", "David Torres",
    "Emma Washington", "James O'Connor", "Priya Singh", "Robert Kim",
    "Fatima Al-Sayed", "William Taylor", "Olivia Martinez", "Lucas Silva",
    "Sophia Reynolds", "Alexander White", "Isabella Gupta", "Daniel Brown",
    "Mia Nguyen", "Ethan Clark", "Ava Robinson", "Noah Lewis"
]

domains = ["techcorp.io", "globalsolutions.net", "innovate.com", "enterprise.org", "startup.co"]
statuses = ["new", "contacted", "interested", "applied", "admitted", "lost"]
priorities = ["high", "medium", "low"]
cities = ["New York", "San Francisco", "London", "Toronto", "Mumbai", "Sydney", "Berlin", "Dubai"]
courses = ["Strategic Management", "Cloud Architecture", "Data Science", "UX Design", "Cybersecurity", "Artificial Intelligence", "Corporate Fin."]
lead_sources = ["Website", "Referral", "Walk-in", "Social Media", "Advertisement", "Other"]

def generate_professional_email(name):
    try:
        first, last = name.split(" ", 1)
        last = last.replace("'", "").replace("-", "")
    except:
        first = name
        last = ""
    formats = [
        f"{first.lower()}.{last.lower()}",
        f"{first.lower()[0]}{last.lower()}",
        f"{first.lower()}_{last.lower()}"
    ]
    return f"{random.choice(formats)}@{random.choice(domains)}"

def generate_phone_number():
    # Generate a realistic 10-digit phone number in the format XXX-XXX-XXXX
    area = random.randint(200, 999)
    prefix = random.randint(200, 999)
    line = random.randint(1000, 9999)
    return f"{area}-{prefix}-{line}"


def seed_leads(db):
    for name in names:
        email = generate_professional_email(name)
        phone_contact = generate_phone_number()
        city = random.choice(cities)
        course = random.choice(courses)
        priority = random.choice(priorities)
        status = random.choice(statuses)
        lead_source = random.choice(lead_sources)
        notes = "Generated by seed script."
        created_at = datetime.utcnow() - timedelta(days=random.randint(0, 30))
        
        try:
            lead = Lead(
                student_name=name,
                phone=phone_contact,
                city=city,
                course_interest=course,
                lead_source=lead_source,
                interest_level=priority,
                status=status,
                notes=notes,
                created_at=created_at,
                lead_score=0
            )
            db.session.add(lead)
            db.session.flush()
            
            lead_id = lead.lead_id
            
            # Create random interactions so the seed data exercises scoring and follow-up widgets
            if random.random() > 0.4:  # 60% chance to have interaction
                for _ in range(random.randint(1, 3)):
                    int_type = random.choice(["call", "email", "whatsapp", "visit"])
                    int_notes = "Spoke about course structure."
                    int_created_at = datetime.utcnow() - timedelta(days=random.randint(1, 40))
                    
                    # 30% chance for an upcoming follow-up to populate that widget
                    follow_up_date = None
                    if random.random() > 0.7:
                        follow_up_date = datetime.now().date() + timedelta(days=random.randint(0, 7))
                    
                    interaction = Interaction(
                        lead_id=lead_id,
                        interaction_type=int_type,
                        notes=int_notes,
                        follow_up_date=follow_up_date,
                        created_at=int_created_at
                    )
                    db.session.add(interaction)

            db.session.flush()
            # Recalculate each lead's score using the live scoring algorithm.
            recalculate_and_persist_score(db, lead_id)

        except Exception as e:
            print(f"Error inserting {name}: {e}")
            db.session.rollback()

if __name__ == "__main__":
    app = create_app()
    with app.app_context():
        db = get_db()
        
        # Optionally clear previous leads for a fresh presentation state
        db.session.query(Interaction).delete()
        db.session.query(Lead).delete()
        db.session.commit()
        
        seed_leads(db)
        db.session.commit()
        print("Successfully seeded database with 20 realistic leads for the presentation!")
